import { useState, useEffect, useRef } from "react";

function useTypewriter(text, speed = 12) {
  const [displayed, setDisplayed] = useState("");
  const [done, setDone] = useState(false);
  const indexRef = useRef(0);

  useEffect(() => {
    if (!text) return;
    setDisplayed("");
    setDone(false);
    indexRef.current = 0;

    const interval = setInterval(() => {
      if (indexRef.current < text.length) {
        setDisplayed(text.slice(0, indexRef.current + 1));
        indexRef.current++;
      } else {
        setDone(true);
        clearInterval(interval);
      }
    }, speed);

    return () => clearInterval(interval);
  }, [text, speed]);

  return { displayed, done };
}

export default function ClinicalSummary({ summary }) {
  const { displayed, done } = useTypewriter(summary, 10);

  if (!summary) return null;

  return (
    <div className="animate-surface-up rounded-2xl border border-cyan-bio/20 bg-navy-800 overflow-hidden shadow-[0_0_40px_rgba(20,255,236,0.08)]">
      <div className="flex items-center gap-2 px-5 py-3 border-b border-cyan-bio/10 bg-navy-900/60">
        <div className="w-2 h-2 rounded-full bg-cyan-bio animate-pulse" />
        <span className="font-mono text-xs tracking-widest uppercase text-cyan-bio/70">
          Clinical Summary — SOAP Format
        </span>
      </div>

      <div className="p-5">
        <pre
          className={`font-mono text-sm text-slate-200 whitespace-pre-wrap leading-relaxed typewriter-text ${
            !done ? "typewriter-cursor" : ""
          }`}
        >
          {displayed}
        </pre>
      </div>

      <div className="px-5 py-3 border-t border-cyan-bio/10 bg-navy-900/40 space-y-1">
        <p className="font-mono text-xs text-cyan-bio/60 font-semibold tracking-wide">
          📋 Save this summary and bring it to your appointment or the ER.
        </p>
        <p className="font-mono text-xs text-slate-500">
          Share it with your doctor, nurse, or triage staff so they have your full picture immediately.
        </p>
        <p className="font-mono text-xs text-slate-600">
          Generated by Depth AI · For physician review only
        </p>
      </div>
    </div>
  );
}
